# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 3000

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: yiyun88
    driverClass: com.mysql.jdbc.Driver

#mybatis.config-location=mybatis-config.xml
mybatis:
  configLocation: classpath:/mybatis-config.xml
  mapperLocations: classpath:/com/ecloudtime/rs/mapper/*.xml